### PR TITLE
inserts barcode button to left of call-no label, toggles selectable b…

### PR DESCRIPTION
**Pull request by mikedaul**
…arcode text on click

### CODE REVIEW

**Comment by mikedaul** [comment]
Weird - must have broken when I rebased. Thanks for noticing it!

**Comment by mikedaul** [comment]
@corylown - should be fixed now :)

**Comment by mikedaul** [comment]
Thanks @seanaery - good feedback. I think the goal at this point was just to get some feedback from stakeholders, so this wasn't intended to be a final version. In any case, I hid the buttons on the index view and also added a script to toggle them all via "shift + b" - not sure that's a good approach either, but it's sorta fun at least :)

**Comment by seanaery** [comment]
@mikedaul Good thinking -- that's a nice revision.

**Pull request merged**
