### PR TITLE
Add Date Cataloged (desc/asc) to options for sorting results. Closes …

### PR DESCRIPTION
**Pull request by seanaery**
…TRLNDSC-201.

### CODE REVIEW

**Comment by seanaery** [comment]
Whoops - have to revise this one for a rubocop rule...

**Comment by seanaery** [comment]
@corylown , @mikedaul OK, ready for review now...

**Comment by corylown** [comment]
@seanaery does this work? I don't think DATE_CATALOGED is mapped to a field that is sortable.

**Comment by seanaery** [comment]
@corylown It also appears to put all the stuff without a Date Cataloged value first in an ascending sort, so we probably don't want an old-to-new option...

**Comment by corylown** [comment]
@seanaery `date_cataloged` probably works directly in the URL, but I think `TrlnArgon::Fields::DATE_CATALOGED` the constant is mapped to `date_cataloged_a` (which doesn't exist). We've not done very much with `date_cataloged` other than power the facet so I think the mapping in trln_argon needs to be updated before this will work. (Which I guess means this PR is fine so long as we then update trln_argon with the correct field mapping.) The sorting empty values first problem is also an issue for publication_date. We have a TRLN backlog issue to deal with it, but it's very unlikely to be resolved before launch.

**Comment by seanaery** [comment]
@corylown Gotcha -- I see what you mean now about that constant. I'll hold off on this for now.

**Pull request closed without merging**
