### PR TITLE
uses dul location service drupal module to populate modal with map an…

### PR DESCRIPTION
**Pull request by mikedaul**
…d/or other messages

### CODE REVIEW

**Comment by mikedaul** [comment]
I just had a thought that I have no idea how to test the map lookup - perhaps not a big deal?

**Comment by mikedaul** [comment]
Thanks @seanaery!

1. The [acceptance criteria](https://duldev.atlassian.net/browse/TRLNDSC-2) specified for this to only display in the show view

2. @corylown  and I had talked about doing this very thing - I agree it's a great idea. We should talk through a good way to implement it!

3. I was trying to give it more prominence (as listed in the 'importance' section of the ticket) than I think it would have just being tacked on to the end, but it's a simple change if we want to do that.

4. So I've never actually written a test before... could I bother you for some assistance with that, please :)

5. Very good idea - I completely forgot to do anything like that.

**Comment by mikedaul** [comment]
@seanaery and @corylown - I believe this should finally be ready for merging. Thanks for all of your help!

**Comment by seanaery** [comment]
Looks good in the UI and the code refactoring looks effective. I support merging. If you have time this sprint, or perhaps for a future sprint, it'd be helpful to clean up the long line lengths & empty lines in `app/views/map_location/show.html.erb`. Rubocop doesn't check .html.erb files but it'd probably flag that file if it did :-)

**Pull request merged**
